---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-common-static
  - clickhouse-client
  - clickhouse-server
clickhouse_config_path: /etc/clickhouse-server/config.xml
clickhouse_users_path: /etc/clickhouse-server/users.xml
clickhouse_user: netology
clickhouse_password: netology

